# Generated by Django 5.2.1 on 2025-05-22 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name.", max_length=50)),
                ('last_name', models.CharField(help_text="Customer's last name.", max_length=50)),
                ('email', models.EmailField(help_text="Customer's email address.", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Customer's phone number (optional).", max_length=20)),
                ('shipping_address_line1', models.CharField(help_text='Shipping address line 1.', max_length=255)),
                ('shipping_address_line2', models.CharField(blank=True, help_text='Shipping address line 2 (optional).', max_length=255)),
                ('shipping_city', models.CharField(help_text='Shipping city.', max_length=100)),
                ('shipping_state', models.CharField(help_text='Shipping state (e.g., OH for Ohio).', max_length=100)),
                ('shipping_zip_code', models.CharField(help_text='Shipping zip code.', max_length=20)),
                ('shipping_country', models.CharField(default='USA', help_text='Shipping country.', max_length=100)),
                ('billing_address_line1', models.CharField(help_text='Billing address line 1.', max_length=255)),
                ('billing_address_line2', models.CharField(blank=True, help_text='Billing address line 2 (optional).', max_length=255)),
                ('billing_city', models.CharField(help_text='Billing city.', max_length=100)),
                ('billing_state', models.CharField(help_text='Billing state.', max_length=100)),
                ('billing_zip_code', models.CharField(help_text='Billing zip code.', max_length=20)),
                ('billing_country', models.CharField(default='USA', help_text='Billing country.', max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price of the order at the time of submission.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('submitted', 'Submitted (Payment Approved)'), ('processed', 'Processed (Shipped)'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the order.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the order was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the order was last updated.')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from the payment gateway.', max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who placed the order (if logged in).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product at time of order.', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Price of the product at time of order.', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the product ordered.')),
                ('order', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order')),
                ('product', models.ForeignKey(blank=True, help_text='The product that was ordered.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ('product_name',),
            },
        ),
    ]
