# Generated by Django 5.2.1 on 2025-05-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Required and unique. Name of the category.', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Required. Unique URL-friendly identifier for the category.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional. A description of the category.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the category was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the category was last updated.')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Required. Name of the product.', max_length=255)),
                ('slug', models.SlugField(help_text='Required. Unique URL-friendly identifier for the product.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional. A detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Required. The price of the product.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Optional. Main image for the product.', null=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to display this product on the homepage as a featured item.')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Required. Current stock level of the product.')),
                ('available', models.BooleanField(default=True, help_text='Designates whether the product is currently available for sale.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the product was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the product was last updated.')),
                ('categories', models.ManyToManyField(help_text='Select one or more categories for this product.', related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name', '-created_at'),
            },
        ),
    ]
