# Generated by Django 5.2.1 on 2025-05-23 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_productvariantattribute_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock quantity for this specific variant', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='products_pr_price_a59bc5_idx'),
        ),
    ]
